server:
  port: 8080

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 000000
  db: qqzone
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
minio:
  endpoint: "127.0.0.1:9000"
  accessKeyID: "root"
  secretAccessKey: "00000000"
  useSSL: false
  bucketName: "Media"
  location: "us-east-1"